name: latihan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
